steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sandboxaq-lqm:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sandboxaq-lqm:latest']
images:
- 'gcr.io/$PROJECT_ID/sandboxaq-lqm:latest'
serviceAccount: supreme-697@acquired-backup-448721-c3.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY


