steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sandboxaq-lqm:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sandboxaq-lqm:$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/sandboxaq-lqm:$COMMIT_SHA'
serviceAccount: supreme-697@acquired-backup-448721-c3.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
